@UrlShortener_HostAddress = http://localhost:5235

POST {{UrlShortener_HostAddress}}/
Accept: application/json
Content-Type: application/json

"https://localhost:7149/swagger/index.html"

###

GET {{UrlShortener_HostAddress}}/2

###
